### ISSUE TITLE
Travis CI testing

### ISSUE THREAD

**Issue by jayvdb** [eye3/nkit4py#2]
It would be good to have a `.travis.yml` running the tests on many versions of Python.

I can set that up if you like.

**Comment by eye3** [comment]
I run tests on travis today and found bug on 2.6 version:) Thanks, John! I fixed it and now builds and tests run w/o problems on python 2.6, 2.7 and >= 3.3 I decided not to support other versions (< 2.6 and < 3.3), may be in the far future: I have no time for this. If you have some ideas about improving .travis.yml, of course you are welcome to make pull request.

**Comment by jayvdb** [comment]
Thank you!
